# Generated by Django 3.2.3 on 2021-07-06 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_auto_20210531_0422"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrganizationListener",
        ),
    ]
