version: "3.8"

services:
  ## entry point for treeckle app containers
  app-reverse-proxy:
    image: jermytan/treeckle-reverse-proxy
    build:
      context: ./app-reverse-proxy
    volumes:
      - static-volume:/app/static
    networks:
      - frontend
      - backend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  ## can only be accessed from same network
  frontend:
    image: jermytan/treeckle-frontend
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://localhost/api
        REACT_APP_GOOGLE_CLIENT_ID: 858509158388-d943lj9isgh7oaumkoj65kqvq1ehgt14.apps.googleusercontent.com
    networks:
      - frontend
    restart: always

  ## can only be accessed from same network
  backend:
    image: jermytan/treeckle-backend
    build:
      context: ./backend
    command: sh -c "cd treeckle && gunicorn treeckle.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static-volume:/app/static
    networks:
      - backend
    restart: always
    env_file:
      - ./backend/.env.backend.local
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env.db.local
    restart: always

networks:
  frontend:
  backend:

volumes:
  postgres-data:
  static-volume:
