# Generated by Django 3.1.3 on 2020-12-19 15:03

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='valid_booking_start_end_date_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='title',
            field=models.CharField(default='Awesome', max_length=255),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(start_date_time__lt=django.db.models.expressions.F('end_date_time')), name='booking_start_date_time_lt_end_date_time'),
        ),
    ]
