# Generated by Django 3.1.3 on 2020-12-07 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='form_data',
            new_name='form_field_data',
        ),
    ]
