# Generated by Django 3.1.3 on 2020-12-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_auto_20201207_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, default=True),
        ),
    ]
