# Generated by Django 3.2.3 on 2021-05-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_auto_20201223_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='venuecategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
