# Generated by Django 3.2.3 on 2021-06-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0010_auto_20210610_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='form_field_data',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
