# Generated by Django 3.2.3 on 2021-06-10 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0011_alter_venue_form_field_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={},
        ),
        migrations.AlterModelOptions(
            name='venuecategory',
            options={},
        ),
    ]
