# Generated by Django 3.2.3 on 2021-06-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0012_auto_20210610_1317"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="venue",
            name="unique_organization_venue_name",
        ),
        migrations.RemoveField(
            model_name="venue",
            name="organization",
        ),
        migrations.AddConstraint(
            model_name="venue",
            constraint=models.UniqueConstraint(
                fields=("category_id", "name"), name="unique_organization_venue_name"
            ),
        ),
    ]
