# Generated by Django 3.2.3 on 2021-06-22 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_auto_20210531_0422"),
        ("venues", "0013_auto_20210622_1642"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="venue",
            name="unique_organization_venue_name",
        ),
        migrations.AddField(
            model_name="venue",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
            preserve_default=False,
        ),
    ]
