# Generated by Django 3.2.3 on 2021-07-06 17:42

from django.db import migrations, models
import django.db.models.deletion
import django_update_from_dict


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0015_venue_unique_organization_venue_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueBookingNotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.venue')),
            ],
            bases=(django_update_from_dict.UpdateFromDictMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='venuebookingnotificationsubscription',
            constraint=models.UniqueConstraint(fields=('email', 'venue_id'), name='unique_email_venue_subscription'),
        ),
    ]
