# Generated by Django 3.2.3 on 2021-07-09 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0016_auto_20210706_1742"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="VenueBookingNotificationSubscription",
            new_name="BookingNotificationSubscription",
        ),
    ]
