# Generated by Django 3.1.3 on 2020-12-07 23:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0003_auto_20201206_1634"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("organized_by", models.CharField(max_length=255)),
                ("venue_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "capacity",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("start_date_time", models.DateTimeField()),
                ("end_date_time", models.DateTimeField()),
                ("image_url", models.URLField()),
                ("image_id", models.CharField(max_length=100)),
                ("is_published", models.BooleanField()),
                ("is_sign_up_allowed", models.BooleanField()),
                ("is_sign_up_approval_required", models.BooleanField()),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="EventCategoryType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="EventSignUp",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("ATTENDED", "Attended"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
            options={
                "ordering": ["-status", "created_at"],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="EventCategoryTypeSubscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.eventcategorytype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.eventcategorytype",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
            ],
            bases=(models.Model,),
        ),
        migrations.AddConstraint(
            model_name="eventsignup",
            constraint=models.UniqueConstraint(
                fields=("user_id", "event_id"), name="unique_user_event_signup"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventcategorytypesubscription",
            constraint=models.UniqueConstraint(
                fields=("category_id", "user_id"),
                name="unique_user_event_category_type_subscription",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventcategorytype",
            constraint=models.UniqueConstraint(
                fields=("name", "organization_id"),
                name="unique_organization_event_category_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventcategory",
            constraint=models.UniqueConstraint(
                fields=("category_id", "event_id"), name="unique_event_category"
            ),
        ),
    ]
