# Generated by Django 3.1.3 on 2020-12-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_auto_20201210_1938"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="organizer",
            new_name="created_by",
        ),
    ]
