# Generated by Django 3.1.3 on 2020-12-23 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('events', '0007_auto_20201219_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategorytype',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
