# Generated by Django 3.2.3 on 2021-06-24 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='bookingcomment',
            name='unique_booking_comment',
        ),
        migrations.AlterField(
            model_name='bookingcomment',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comments.comment'),
        ),
    ]
