# Generated by Django 3.1.3 on 2020-11-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["role", "name"]},
        ),
        migrations.AlterModelOptions(
            name="userinvite",
            options={"ordering": ["role", "email"]},
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Organizer", "Organizer"),
                    ("Resident", "Resident"),
                ],
                default="Resident",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userinvite",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Organizer", "Organizer"),
                    ("Resident", "Resident"),
                ],
                default="Resident",
                max_length=50,
            ),
        ),
    ]
