# Generated by Django 3.1.3 on 2020-12-09 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20201206_1634"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="userinvite",
            options={"ordering": ["email"]},
        ),
    ]
