# Generated by Django 3.2.3 on 2021-06-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_auto_20210531_0422"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterModelOptions(
            name="userinvite",
            options={},
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.URLField(null=True),
        ),
    ]
