# Generated by Django 3.2.3 on 2021-07-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20210609_1228"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
