# Generated by Django 3.2.5 on 2021-07-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_user_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_image",
        ),
    ]
