# Generated by Django 3.2.3 on 2021-07-13 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_name'),
        ('authentication', '0003_auto_20210709_1926'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GmailAuthentication',
            new_name='GoogleAuthentication',
        ),
    ]
