name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          command_timeout: 60m
          script: |
            ls
            cd /home/treeckle/Treeckle-3.0

            # Temp store changes
            git stash

            # Pull from git repo
            git checkout master || true # Force return true so exit code is not 1
            git pull

            # Clear space
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker image prune -f

            # Build
            cd frontend
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S bash ./build-prod.sh
            cd ..
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker-compose -f ./docker-compose.prod.yml up -d

            # Restore changes
            git stash pop || true # Force return true in case no changes stashed
